### ISSUE TITLE
Can't run behind Traefik

### ISSUE THREAD

**Issue by pavanfhw** [Okazanta/Dockerized#4]
My compose (irrelevant parts omitted): 

```
okazanta:
  image: my.registry.okazanta
  expose:
    - "8000"
  labels:
    - traefik.enable=true
    - traefik.http.routers.service.middlewares=strip-prefix@file
    - traefik.http.routers.service.rule=PathPrefix(`/status`)
    - traefik.http.routers.service.tls=true
    - traefik.http.services.service.loadbalancer.server.port=8000
 ```
 
 Only the first request works. All others requests to css and js files get 404
  
![image](https://user-images.githubusercontent.com/69058540/219784176-956d5e45-586c-4e52-8ca3-d1a4cc7c215b.png)

The first request is made to `host.com/status` and get 200. All others are made without the prefix, for example:
```
myhost.com/dist/css.... # 404, it should be myhost.com/status/dist/css...
myhost.com/dist/js.... # 404, it should be myhost.com/status/dist/js...
```

All other services in the compose work correctly. I imagine there is a config in nginx or php redirecting that makes it not work behind traefik. 

Nginx log when I open `myhost.com/status` on the browser:
```
"GET / HTTP/1.1" 200 14292 "-"
```
Nothing more
